# Generated by Django 2.1.5 on 2019-02-11 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horasLaborables', models.IntegerField(null=True)),
                ('horasVacaciones', models.IntegerField(null=True)),
                ('horasEnfermedad', models.IntegerField(null=True)),
                ('horasEspeciales', models.IntegerField(null=True)),
                ('horasPorcentaje', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idEmpleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apPaterno', models.CharField(max_length=50)),
                ('apMaterno', models.CharField(max_length=50, null=True)),
                ('mail', models.EmailField(max_length=50, null=True)),
                ('area', models.CharField(max_length=50, null=True)),
                ('activo', models.IntegerField()),
                ('pais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ftes',
            fields=[
                ('nombreFtes', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('activo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('clavePeriodo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('horasTotales', models.IntegerField()),
                ('horasNoLaborables', models.IntegerField(null=True)),
                ('descripcionMes', models.CharField(max_length=20)),
                ('descripcionAnio', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('codigo', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.IntegerField(null=True)),
                ('nombreFtes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Ftes')),
            ],
        ),
        migrations.AddField(
            model_name='bitacora',
            name='clavePeriodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Periodo'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Proyecto'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='idEmpleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Empleado'),
        ),
        migrations.AlterUniqueTogether(
            name='bitacora',
            unique_together={('idEmpleado', 'codigo', 'clavePeriodo')},
        ),
    ]
