# Generated by Django 2.1.5 on 2019-02-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_bitacora_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='observaciones',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
