# Generated by Django 2.1.5 on 2019-02-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190214_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='horasEnfermedad',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='horasEspeciales',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='horasLaborables',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='horasPorcentaje',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='horasVacaciones',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='observaciones',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
