# Generated by Django 2.1.5 on 2019-02-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190214_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='horasLaborables',
            field=models.FloatField(default=0, null=True),
        ),
    ]
